<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

#### Exercise 1


|  Term   |  Description   |
| :---    |  :---  | 
|  Subsetting  | _Subsetting means to 'select'._   |
|  Indexing  | Indexing refers to choosing a single item in a list or array.   |
|  Slicing  | Slicing refers to choosing a few items in a list or array.   |
|  Masking  | _Masking lets one subset NumPy arrays._   |



#### Exercise 2

In [ ]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])


# Index from 0 to 10 for 1st element only
np_array_number = np_array_2d[:, 0]

# astype(int) changes string to number
np_array_int = np_array_number.astype(int)
np_array_div2 = np_array_int % 2

# Returns true or false depending on odd or even
parity = np_array_div2 == 1


odd_letters = np_array_2d[parity, 1]
print(odd_letters)

['A' 'C' 'E' 'G' 'I']


#### Exercise 3

In [40]:
array = np.array([[66, 50, 57, -1, -1],
                  [92, -1, 88, -1, -1],
                  [75, -1, -1, 76, -1],
                  [-1, 51, 87, -1, -1],
                  [71, -1, 67, -1, 69]])

above_fifty = array > 50
below_fifty = array < 50
exact_fifty = array == 50

array[above_fifty] = 1
array[below_fifty] = -1
array[exact_fifty] = 0

print(array)


[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
